#multi_session.yaml

multi_session:

  sessions_dir: "/home/li/" 

  central_sess_name: "01" # should be same as the directory name of that session
  query_sess_name: "06" # should be same as the directory name of that session
  
  save_directory: "0106" 

  iteration: 3
